language: c

sudo: false

addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libpq-dev

services:
  - mysql
  - postgresql

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
      # Lua 5.1 on different DBs
      - LUA=lua5.1 DB_DRIVER=mysql DB_USER=travis DB_NAME=sailor_test
      - LUA=lua5.1 DB_DRIVER=postgres DB_USER=postgres DB_NAME=sailor_test
      - LUA=lua5.1 DB_DRIVER=sqlite3 DB_USER="" DB_NAME=$TRAVIS_BUILD_DIR/sailor_test
      # Lua 5.2 on different DBs
      - LUA=lua5.2 DB_DRIVER=mysql DB_USER=travis DB_NAME=sailor_test
      - LUA=lua5.2 DB_DRIVER=postgres DB_USER=postgres DB_NAME=sailor_test
      - LUA=lua5.2 DB_DRIVER=sqlite3 DB_USER="" DB_NAME=$TRAVIS_BUILD_DIR/sailor_test
      # LuaJIT latest stable version (2.0.4) on different DBs
      - LUA=luajit DB_DRIVER=mysql DB_USER=travis DB_NAME=sailor_test
      - LUA=luajit DB_DRIVER=postgres DB_USER=postgres DB_NAME=sailor_test
      - LUA=luajit DB_DRIVER=sqlite3 DB_USER="" DB_NAME=$TRAVIS_BUILD_DIR/sailor_test
      # Openresty + LuaJIT + mysql
      - LUA=luajit SERVER=openresty DB_DRIVER=mysql DB_USER=travis DB_NAME=sailor_test 
      # - LUA=luajit2.0  # current head of 2.0 branch
      # - LUA=luajit2.1  # current head of 2.1 branch
      # Not supported
      # - LUA=lua5.2 

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks make rockspecs/sailor-current-1.rockspec

before_script:
  - source .travis/setdatabases.sh

script:
  - cd test/dev-app
  - if [ "$SERVER" != "openresty" ]; then sailor test -- --verbose --coverage; fi
  - if [ "$SERVER" == "openresty" ]; then sailor test --resty; fi

after_success:
  - mv luacov.stats.out ../..
  - cd ../..
  - luacov-coveralls -c test/dev-app/.luacov

notifications:
  email:
    on_success: change
    on_failure: always
